### ISSUE TITLE
Savefile's preparation of the data to then write it into a file should be multi-threaded

### ISSUE THREAD

**Issue by gabrielmfern** [avl/savefile#26] opened 2022-09-22 21:42 UTC
I am working with really large files and multi-threading can really help me out if implemented into Savefile.
I'm not really sure just how Savefile does the preparation of the data before writing it into a file because I have not read the code, but I imagine it would be really simple using the rayon crate.

Saving the files in the computer currently takes about 5-10 minutes as they are really large, so multithreading could REALLY improve this for saving and loading these types of files multiple times. Perhaps even you could make that optional somehow, some kind of feature that contains a `save_file_par(...)` function that could work.

**Comment by avl** [comment] 2022-09-23 06:41
Hello!

Thank you very much for your feature request!

Multithreading is an interesting idea. 

However, first, I would like to understand _why_ your usecase is slow. Savefile serialization is meant to be very fast. 

I have a few questions!

a) Are you using nightly rust, or stable? Unfortunately, savefile can be slow for big arrays on nightly, due to the "ReprC"-feature not being available (as it requires the rust-feature "specialization"). It might be possible to do something here though.

b) What kind of objects are you serializing? Any arrays with many small elements? Hashmaps? BitVec is known to be slow (but a fix is in the works).

c) How big are the files, once you've saved them to disk? Ideally I'd expect savefile to be able to serialize at speeds above 1 GB/s.

d) Are you using the built-in compression/encryption-feature?

e) Is saving slower than loading? 

f) Is there a big different in serialization speed in debug vs release-builds? Are release-builds also annoyingly slow? If release-builds are fast, you can configure cargo to compile savefile in release-mode and still compile the rest of your app in debug-mode.

**Comment by gabrielmfern** [comment] 2022-09-23 11:07
> Hello!
> 
> Thank you very much for your feature request!
> 
> Multithreading is an interesting idea.
> 
> However, first, I would like to understand _why_ your usecase is slow. Savefile serialization is meant to be very fast.
> 
> I have a few questions!
> 
> a) Are you using nightly rust, or stable? Unfortunately, savefile can be slow for big arrays on nightly, due to the "ReprC"-feature not being available (as it requires the rust-feature "specialization"). It might be possible to do something here though.
> 
> b) What kind of objects are you serializing? Any arrays with many small elements? Hashmaps? BitVec is known to be slow (but a fix is in the works).
> 
> c) How big are the files, once you've saved them to disk? Ideally I'd expect savefile to be able to serialize at speeds above 1 GB/s.
> 
> d) Are you using the built-in compression/encryption-feature?
> 
> e) Is saving slower than loading?
> 
> f) Is there a big different in serialization speed in debug vs release-builds? Are release-builds also annoyingly slow? If release-builds are fast, you can configure cargo to compile savefile in release-mode and still compile the rest of your app in debug-mode.

a) I am not using nightly, but I'll try to see if things improve

b) I'd say arrays with many small elements, some structs that contain some text

c) The files that I'm saving are around 1GB

d) I'm not quite sure, do I need to enable it in the Cargo.toml for Savefile?

e) I think it is though I'm not quite sure because I haven't measured so I'd say just a bit slower

f) I'm always running using release-builds since I needed it running as fast as possible, so I'm not sure if Savefile's much faster in release mode.

Although I do think if I start breaking my data down into multiple files I can get it to go much faster, since these chunks would be around 10mb-20mb.
Another thing is that I was loading the data from the disk (which I don't think is ideal) everytime I needed to update it, as to add things into the array and I'm quite sure now that the slowest part was actually adding the data into the Vec instead of saving small chunks and adding it all after. Also, I am not using a m.2 drive so that may impact the saving speeds a bit as well.

**Comment by avl** [comment] 2022-09-23 12:03
Thank you very much for your response!

I have a theory of what the problem is. 

I've created a fix, you can try it by specifying this in your Cargo.toml:

```
savefile={ git = "https://github.com/avl/savefile", branch = "master" }
savefile-derive={ git = "https://github.com/avl/savefile", branch = "master" }
```

If my theory is correct, it's a bit embarassing :-) . 

Are you perhaps using the functions 'save_file' and 'load_file'?  If so, that is perfectly fine. Or should have been perfectly fine.

I just realized these don't do any buffering. So every single little write would lead to an operating system write call. This would become hideously slow.

I haven't noticed, since I'm not using those functions directly.

I would be very interested to hear if this resolves your problem!

The ReprC-stuff can also improve performance a lot, but might not be applicable if you have String-objects in your data.

**Comment by gabrielmfern** [comment] 2022-09-24 11:53
Wow thanks, I think this made quite a difference, for something like a array of 60k items of the struct I am using (resulting in 10mb), it saved it in around 80ms-60ms. Before, I think, it was taking a few seconds although I haven't computed it.

I didn't test for those big files as before because I've changed it to saving it in separate files, but I will compute how long it takes to save when I put all of the data together.

**Comment by avl** [comment] 2022-09-24 12:40
Interesting!

I've been thinking about how to implement multi-threading. I think it might be tricky to do well, unless major changes are made.

One problem is that the API to Savefile presently only requires objects which implement Read for deserializing, and Write for serializing. There's no way to parallelize the actual reading/writing-part. So to parallelize, one would have to use some sort of temporary buffer. 

Another problem is that Savefile doesn't present a way to determine ahead-of-time how large an object will become once serialized. So the only way to parallelize serialization of a sequence would be to serialize each item to its own temporary buffer, and then join these buffers. I have some experience writing a serialization framework which did have support for statically known sizes. It can be tricky. For example, the only way to determine the size of something like Vec<String> is to actually scan over it once.

Ideally I would like for savefile to be so fast that it basically doesn't need to be parallelized. 

Please get back to me if you still feel that savefile is the bottleneck after this fix to buffering!

**Comment by gabrielmfern** [comment] 2022-09-24 14:56
I have put the data together and it seems that for the loading time of a 1.1gb file with my structs took ~37s
as for the saving of the new data (~2.6gb) it took ~19s compared to taking around minutes before with a 1gb file.
Compared to before it is much, much better. I'm not sure if the loading should've been faster than the saving though.

I don't really understand what you said about the problems of trying to parallelize the saving process, but perhaps, just focusing on serialization, you could first break the data into parts and send them each to as many threads as possible based on the amount of cores, and then collect the data from each thread into just one big block of serialized data, that is, if you don't need to update the data over and over again around the same places and can't really separate into blocks.
But I think I'm quite happy with how fast it is now compared to before.

**Comment by avl** [comment] 2022-09-25 15:56
Thanks for your report!

I'm not entirely happy that saving ~2.6GB data takes 19 seconds. This is in release-mode, right? 

Can you give me some example of how your datastructure looks? I would have hoped performance would be much better than that!

**Comment by gabrielmfern** [comment] 2022-09-27 10:25
Yes, this is in release mode as well as with nightly. Sorry for the time taken to answer, been busy with work. my datastructure is basically just this:
```rust
struct Category {
    parent: String,
    category: String,
    url: String
}

struct Sample {
   name: String,
   category: Category
}
```
and then I am just saving and loading a big Vec of these samples with some millions of these. Both of these do derive Savefile, Debug and Clone if that is useful.

**Comment by avl** [comment] 2022-09-27 11:15
Thank you!

I tried something similar, and I can confirm the disappointing performance.

Most of the time is probably spent chasing pointers in memory. 

I know you said you're basically ok with performance now. So I don't know if you're interested in further optimization.

But if you are!:

If you can live with size-limits for all the strings, you may be able to optimize this by changing from String to ArrayString from arrayvec crate, and using the savefile 'reprc' feature. This requires nightly compiler. 

Anyway, this is only an option if your strings have (reasonably small) known maximum sizes.

Something like this:

```rust
#[derive(ReprC, Clone, Copy, Savefile)]
#[repr(C)]
struct Category {
    parent: ArrayString,
    category: ArrayString,
    url: ArrayString
}
```
However, I'm entirely sure if this would work right now. I'll investigate when I get time!

I also tried parallelizing saves using rayon. I didn't manage to make it run any faster though. In my experience it is often tricky to gain performance by parallelizing when the memory subsystem is the bottleneck. In principle though, it might not be impossible! Savefile presently does not serialize at even close to theoretical max memory bandwidth (because of various reasons including locality of reference and latency).

**Comment by avl** [comment] 2022-09-27 19:49
I've done some more investigation.

The following program:

```rust
pub fn test_many_arraystrings() {
    let mut outer:Vec<Vec<ArrayString<20>>> = Vec::new();
    for _ in 0..100 {
        let mut inner = vec![];
        for _ in 0..1000_000 {
            inner.push("Test thing".try_into().unwrap());
        }
        outer.push(inner);
    }
    let mut f = Cursor::new(Vec::with_capacity(2_000_000_000));
    {
        let t = Instant::now();
        Serializer::save_noschema(&mut f, 1, &outer).unwrap();
        println!("Save-Time: {}", speed(f.get_ref().len(),t.elapsed()));
    }
    {
        let t = Instant::now();
        f.set_position(0);
        let deserialized : Vec<Vec<ArrayString<20>>> = Deserializer::load_noschema(&mut f, 1).unwrap();
        println!("Load-Time: {} (last value: {})",  speed(f.get_ref().len(),t.elapsed()), deserialized.last().unwrap().last().unwrap());
    }

    println!("Size: {}", f.get_ref().len() as f64 / 1e9f64);
}
```

Achieves a serialization speed of approximately 3GB/s (on my Ryzen 5950X machine). The same program using Strings uses more time, especially for deserialization (because of memory allocation overhead, presumably). 

For arraystrings:
```rust
Save-Time: 2400000824 bytes in 0.68s = 3.518521083997332 GB/sec
Load-Time: 2400000824 bytes in 0.67s = 3.597015712958245 GB/sec (last value: Test thing)
```

For String:

```rust
Save-Time: 1800000824 bytes in 1.27s = 1.4139289406770674 GB/sec
Load-Time: 1800000824 bytes in 3.87s = 0.46466455468118345 GB/sec (last value: Test thing)
```

I believe this is now acceptable performance. I think it's going to be very hard to speed this up using parallelization. Doing this also is likely to require that the types Savefile operates on are Sync, which is not presently required (though this could be managed using an optional feature) .

Unless someone can come up with a compelling PR, I'm going to close this issue, with the resoluition to not add multithreading to savefile.

Thanks again for helping to improve Savefile, and please reopen if you want to discuss this further!

**Closed** 2022-09-27 19:49 UTC
